import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../domain/models/goods_receipt_note.dart';
import '../../../../providers/goods_receipt_note_provider.dart';

class CreateGRNScreen extends ConsumerStatefulWidget {
  const CreateGRNScreen({super.key});

  @override
  ConsumerState<CreateGRNScreen> createState() => _CreateGRNScreenState();
}

class _CreateGRNScreenState extends ConsumerState<CreateGRNScreen> {
  final _formKey = GlobalKey<FormState>();
  final _deliveryNoteController = TextEditingController();
  final _vehicleNumberController = TextEditingController();
  final _storageLocationController = TextEditingController();

  String? _purchaseOrderId;
  String? _supplierId;
  String? _receivedById;
  String? _storekeeperId;
  DateTime? _receiptDate;
  final List<GRNItem> _items = [];

  bool _isSubmitting = false;

  @override
  void dispose() {
    _deliveryNoteController.dispose();
    _vehicleNumberController.dispose();
    _storageLocationController.dispose();
    super.dispose();
  }

  Future<void> _submitForm() async {
    if (!_formKey.currentState!.validate()) return;
    if (_purchaseOrderId == null ||
        _supplierId == null ||
        _receivedById == null ||
        _storekeeperId == null ||
        _receiptDate == null ||
        _items.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please fill all required fields and add at least one item')),
      );
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      final grn = GoodsReceiptNote(
        id: '',
        grnNumber: '', // Will be generated by backend
        purchaseOrderId: _purchaseOrderId!,
        purchaseOrderNumber: 'PO-123', // You'll need to get this from PO provider
        supplierId: _supplierId!,
        supplierName: 'Supplier Name', // You'll need to get this from supplier provider
        receiptDate: _receiptDate!,
        receivedById: _receivedById!,
        receivedByName: 'User Name', // You'll need to get this from user provider
        deliveryNoteNumber: _deliveryNoteController.text.isEmpty ? null : _deliveryNoteController.text,
        vehicleNumber: _vehicleNumberController.text.isEmpty ? null : _vehicleNumberController.text,
        items: _items,
        totalQuantity: _items.fold(0, (sum, item) => sum + item.receivedQuantity),
        totalValue: _items.fold(0.0, (sum, item) => sum + item.totalValue),
        qualityStatus: 'pending',
        storageLocation: _storageLocationController.text,
        storekeeperId: _storekeeperId!,
        storekeeperName: 'Storekeeper Name', // You'll need to get this from user provider
        status: 'draft',
        hasReturns: false,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      await ref.read(goodsReceiptNotesProvider.notifier).createGRN(grn);

      if (mounted) {
        Navigator.of(context).pop();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('GRN created successfully')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to create GRN: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isSubmitting = false);
      }
    }
  }

  void _addItem() {
    showDialog(
      context: context,
      builder: (context) => AddGRNItemDialog(
        onItemAdded: (item) {
          setState(() {
            _items.add(item);
          });
        },
      ),
    );
  }

  void _removeItem(int index) {
    setState(() {
      _items.removeAt(index);
    });
  }

  Future<void> _selectReceiptDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(2000),
      lastDate: DateTime(2100),
    );
    if (picked != null) {
      setState(() => _receiptDate = picked);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Goods Receipt Note'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              // Purchase Order Selection
              DropdownButtonFormField<String>(
                value: _purchaseOrderId,
                decoration: const InputDecoration(
                  labelText: 'Purchase Order*',
                  border: OutlineInputBorder(),
                ),
                items: [
                  // You'll need to populate this from a PO provider
                  DropdownMenuItem(value: 'po1', child: Text('PO-001')),
                  DropdownMenuItem(value: 'po2', child: Text('PO-002')),
                ],
                onChanged: (value) => setState(() => _purchaseOrderId = value),
                validator: (value) => value == null ? 'Please select purchase order' : null,
              ),
              const SizedBox(height: 16),

              // Supplier Selection
              DropdownButtonFormField<String>(
                value: _supplierId,
                decoration: const InputDecoration(
                  labelText: 'Supplier*',
                  border: OutlineInputBorder(),
                ),
                items: [
                  // You'll need to populate this from a supplier provider
                  DropdownMenuItem(value: 'sup1', child: Text('Supplier 1')),
                  DropdownMenuItem(value: 'sup2', child: Text('Supplier 2')),
                ],
                onChanged: (value) => setState(() => _supplierId = value),
                validator: (value) => value == null ? 'Please select supplier' : null,
              ),
              const SizedBox(height: 16),

              // Receipt Date
              InkWell(
                onTap: _selectReceiptDate,
                child: InputDecorator(
                  decoration: const InputDecoration(
                    labelText: 'Receipt Date*',
                    border: OutlineInputBorder(),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(_receiptDate != null
                          ? _formatDate(_receiptDate!)
                          : 'Select date'),
                      const Icon(Icons.calendar_today),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Received By
              DropdownButtonFormField<String>(
                value: _receivedById,
                decoration: const InputDecoration(
                  labelText: 'Received By*',
                  border: OutlineInputBorder(),
                ),
                items: [
                  // You'll need to populate this from a user provider
                  DropdownMenuItem(value: 'user1', child: Text('John Doe')),
                  DropdownMenuItem(value: 'user2', child: Text('Jane Smith')),
                ],
                onChanged: (value) => setState(() => _receivedById = value),
                validator: (value) => value == null ? 'Please select receiver' : null,
              ),
              const SizedBox(height: 16),

              // Storekeeper
              DropdownButtonFormField<String>(
                value: _storekeeperId,
                decoration: const InputDecoration(
                  labelText: 'Storekeeper*',
                  border: OutlineInputBorder(),
                ),
                items: [
                  // You'll need to populate this from a user provider
                  DropdownMenuItem(value: 'user3', child: Text('Storekeeper 1')),
                  DropdownMenuItem(value: 'user4', child: Text('Storekeeper 2')),
                ],
                onChanged: (value) => setState(() => _storekeeperId = value),
                validator: (value) => value == null ? 'Please select storekeeper' : null,
              ),
              const SizedBox(height: 16),

              // Optional Fields
              TextFormField(
                controller: _deliveryNoteController,
                decoration: const InputDecoration(
                  labelText: 'Delivery Note Number',
                  border: OutlineInputBorder(),
                ),
              ),
              const SizedBox(height: 16),

              TextFormField(
                controller: _vehicleNumberController,
                decoration: const InputDecoration(
                  labelText: 'Vehicle Number',
                  border: OutlineInputBorder(),
                ),
              ),
              const SizedBox(height: 16),

              TextFormField(
                controller: _storageLocationController,
                decoration: const InputDecoration(
                  labelText: 'Storage Location*',
                  border: OutlineInputBorder(),
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter storage location';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 24),

              // Items Section
              Row(
                children: [
                  const Text(
                    'Items',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                  const Spacer(),
                  ElevatedButton.icon(
                    onPressed: _addItem,
                    icon: const Icon(Icons.add),
                    label: const Text('Add Item'),
                  ),
                ],
              ),
              const SizedBox(height: 12),

              if (_items.isEmpty)
                const Center(
                  child: Text(
                    'No items added',
                    style: TextStyle(color: Colors.grey),
                  ),
                ),

              ..._items.asMap().entries.map((entry) {
                final index = entry.key;
                final item = entry.value;
                return _buildItemCard(item, index);
              }).toList(),

              const SizedBox(height: 32),

              // Submit Button
              ElevatedButton(
                onPressed: _isSubmitting ? null : _submitForm,
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                ),
                child: _isSubmitting
                    ? const SizedBox(
                  height: 20,
                  width: 20,
                  child: CircularProgressIndicator(strokeWidth: 2),
                )
                    : const Text('Create GRN'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildItemCard(GRNItem item, int index) {
    return Card(
      margin: const EdgeInsets.only(bottom: 8),
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Row(
          children: [
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    item.description,
                    style: const TextStyle(fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 4),
                  Text('PO Item: ${item.poItem}'),
                  Text('Qty: ${item.receivedQuantity} ${item.unit}'),
                  Text('Value: KES ${item.totalValue.toStringAsFixed(2)}'),
                ],
              ),
            ),
            IconButton(
              onPressed: () => _removeItem(index),
              icon: const Icon(Icons.delete, color: Colors.red),
            ),
          ],
        ),
      ),
    );
  }

  String _formatDate(DateTime date) {
    return '${date.day}/${date.month}/${date.year}';
  }
}

class AddGRNItemDialog extends StatefulWidget {
  final Function(GRNItem) onItemAdded;

  const AddGRNItemDialog({super.key, required this.onItemAdded});

  @override
  State<AddGRNItemDialog> createState() => _AddGRNItemDialogState();
}

class _AddGRNItemDialogState extends State<AddGRNItemDialog> {
  final _formKey = GlobalKey<FormState>();
  final _poItemController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _orderedQuantityController = TextEditingController();
  final _receivedQuantityController = TextEditingController();
  final _unitController = TextEditingController();
  final _unitPriceController = TextEditingController();

  @override
  void dispose() {
    _poItemController.dispose();
    _descriptionController.dispose();
    _orderedQuantityController.dispose();
    _receivedQuantityController.dispose();
    _unitController.dispose();
    _unitPriceController.dispose();
    super.dispose();
  }

  void _addItem() {
    if (_formKey.currentState!.validate()) {
      final item = GRNItem(
        poItem: _poItemController.text,
        description: _descriptionController.text,
        orderedQuantity: int.parse(_orderedQuantityController.text),
        receivedQuantity: int.parse(_receivedQuantityController.text),
        acceptedQuantity: 0,
        rejectedQuantity: 0,
        unit: _unitController.text,
        unitPrice: double.parse(_unitPriceController.text),
        totalValue: double.parse(_unitPriceController.text) * int.parse(_receivedQuantityController.text),
        status: 'pending',
      );

      widget.onItemAdded(item);
      Navigator.of(context).pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Add GRN Item'),
      content: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TextFormField(
                controller: _poItemController,
                decoration: const InputDecoration(
                  labelText: 'PO Item Code*',
                  border: OutlineInputBorder(),
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter PO item code';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _descriptionController,
                decoration: const InputDecoration(
                  labelText: 'Description*',
                  border: OutlineInputBorder(),
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter description';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _orderedQuantityController,
                      decoration: const InputDecoration(
                        labelText: 'Ordered Qty*',
                        border: OutlineInputBorder(),
                      ),
                      keyboardType: TextInputType.number,
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Please enter ordered quantity';
                        }
                        if (int.tryParse(value) == null) {
                          return 'Please enter valid number';
                        }
                        return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: TextFormField(
                      controller: _receivedQuantityController,
                      decoration: const InputDecoration(
                        labelText: 'Received Qty*',
                        border: OutlineInputBorder(),
                      ),
                      keyboardType: TextInputType.number,
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Please enter received quantity';
                        }
                        if (int.tryParse(value) == null) {
                          return 'Please enter valid number';
                        }
                        return null;
                      },
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _unitController,
                      decoration: const InputDecoration(
                        labelText: 'Unit*',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Please enter unit';
                        }
                        return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: TextFormField(
                      controller: _unitPriceController,
                      decoration: const InputDecoration(
                        labelText: 'Unit Price*',
                        border: OutlineInputBorder(),
                        prefixText: 'KES ',
                      ),
                      keyboardType: TextInputType.number,
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Please enter unit price';
                        }
                        if (double.tryParse(value) == null) {
                          return 'Please enter valid number';
                        }
                        return null;
                      },
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: _addItem,
          child: const Text('Add Item'),
        ),
      ],
    );
  }
}